name: Sieu Bot Diet Lazi Rep Chat Bang QuillBot
on:
  workflow_dispatch: # Bật phát đầu, sau bot tự gọi nhau

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 1. Tự khôi phục Cache (Node modules & Chrome) nếu đã có
    - name: Cache Node Modules & Chrome
      uses: actions/cache@v4
      id: global-cache
      with:
        path: |
          ~/.npm
          ~/.cache/puppeteer
          node_modules
        key: ${{ runner.os }}-bot-deps-v2-${{ hashFiles('package.json') }}

    # 2. Bổ sung puppeteer-extra và puppeteer-extra-plugin-stealth vào lệnh cài
    - name: Install Dependencies & Chrome Binary
      if: steps.global-cache.outputs.cache-hit != 'true'
      run: |
        npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios form-data
        npx puppeteer browsers install chrome

    - name: Khoi chay he thong AI rep chat tu dong
      run: node bot.js
      env:
        GH_TOKEN: ${{ github.token }}
